my_string = input('Введите произвольный текст: ')
print('Количество символов в введенном  тексте: ', len(my_string))
print('Строка в верхнем регистре:', my_string .upper())
print('Строка в нижнем регистре:', my_string .lower())
print('Строка в без пробелов:', my_string .replace(' ', '_'))
print('Первый символ строки:', my_string[0])
print('Последний символ строки: ', my_string[-1])